# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter_tuning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameter_tuning.proto',
  package='hptuning',
  syntax='proto3',
  serialized_options=_b('\n\026sun.portfolio.hptuning'),
  serialized_pb=_b('\n\x16parameter_tuning.proto\x12\x08hptuning\"D\n\x0bpara_define\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x01\x12\n\n\x02\x64t\x18\x03 \x01(\x03\x12\x0c\n\x04step\x18\x04 \x01(\x01\"\x14\n\x04\x66lag\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\"6\n\tparameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"%\n\x06metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"o\n\x10parameter_result\x12.\n\x11parameter_setting\x18\x01 \x03(\x0b\x32\x13.hptuning.parameter\x12+\n\x11parameter_metrics\x18\x02 \x03(\x0b\x32\x10.hptuning.metric\"@\n\x11parameter_results\x12+\n\x07records\x18\x01 \x03(\x0b\x32\x1a.hptuning.parameter_result\"h\n\x0ehptuning_tasks\x12)\n\x05tasks\x18\x01 \x03(\x0b\x32\x1a.hptuning.parameter_result\x12+\n\x07optimal\x18\x02 \x03(\x0b\x32\x1a.hptuning.parameter_result\"/\n\x0e\x62\x61lanced_dates\x12\r\n\x05param\x18\x01 \x01(\x03\x12\x0e\n\x06method\x18\x02 \x01(\t\"\xd9\x01\n\x06\x63onfig\x12\x11\n\tbenchmark\x18\x01 \x01(\t\x12\x1c\n\x14\x65xpected_return_days\x18\x02 \x01(\x03\x12\x0e\n\x06stocks\x18\x03 \x03(\t\x12\x17\n\x0finitial_capital\x18\x04 \x01(\x01\x12\r\n\x05start\x18\x05 \x01(\x03\x12\x10\n\x08stragety\x18\x06 \x01(\t\x12.\n\x0c\x62\x61lancedDays\x18\x07 \x01(\x0b\x32\x18.hptuning.balanced_dates\x12\x0b\n\x03\x65nd\x18\x08 \x01(\x03\x12\x17\n\x0f\x63leaned_weights\x18\t \x01(\x08\"\\\n\x0ctasks_difine\x12%\n\x06params\x18\x01 \x03(\x0b\x32\x15.hptuning.para_define\x12%\n\x0btask_config\x18\x02 \x01(\x0b\x32\x10.hptuning.config2x\n\x08hptuning\x12>\n\ngridsearch\x12\x16.hptuning.tasks_difine\x1a\x18.hptuning.hptuning_tasks\x12,\n\nstopServer\x12\x0e.hptuning.flag\x1a\x0e.hptuning.flagB\x18\n\x16sun.portfolio.hptuningb\x06proto3')
)




_PARA_DEFINE = _descriptor.Descriptor(
  name='para_define',
  full_name='hptuning.para_define',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hptuning.para_define.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='hptuning.para_define.start', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dt', full_name='hptuning.para_define.dt', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='hptuning.para_define.step', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=104,
)


_FLAG = _descriptor.Descriptor(
  name='flag',
  full_name='hptuning.flag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='hptuning.flag.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=126,
)


_PARAMETER = _descriptor.Descriptor(
  name='parameter',
  full_name='hptuning.parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hptuning.parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='hptuning.parameter.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hptuning.parameter.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=182,
)


_METRIC = _descriptor.Descriptor(
  name='metric',
  full_name='hptuning.metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hptuning.metric.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hptuning.metric.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=221,
)


_PARAMETER_RESULT = _descriptor.Descriptor(
  name='parameter_result',
  full_name='hptuning.parameter_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter_setting', full_name='hptuning.parameter_result.parameter_setting', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter_metrics', full_name='hptuning.parameter_result.parameter_metrics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=334,
)


_PARAMETER_RESULTS = _descriptor.Descriptor(
  name='parameter_results',
  full_name='hptuning.parameter_results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='hptuning.parameter_results.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=400,
)


_HPTUNING_TASKS = _descriptor.Descriptor(
  name='hptuning_tasks',
  full_name='hptuning.hptuning_tasks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='hptuning.hptuning_tasks.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optimal', full_name='hptuning.hptuning_tasks.optimal', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=506,
)


_BALANCED_DATES = _descriptor.Descriptor(
  name='balanced_dates',
  full_name='hptuning.balanced_dates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='hptuning.balanced_dates.param', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='hptuning.balanced_dates.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=555,
)


_CONFIG = _descriptor.Descriptor(
  name='config',
  full_name='hptuning.config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='benchmark', full_name='hptuning.config.benchmark', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_return_days', full_name='hptuning.config.expected_return_days', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stocks', full_name='hptuning.config.stocks', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_capital', full_name='hptuning.config.initial_capital', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='hptuning.config.start', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stragety', full_name='hptuning.config.stragety', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balancedDays', full_name='hptuning.config.balancedDays', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='hptuning.config.end', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cleaned_weights', full_name='hptuning.config.cleaned_weights', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=775,
)


_TASKS_DIFINE = _descriptor.Descriptor(
  name='tasks_difine',
  full_name='hptuning.tasks_difine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='hptuning.tasks_difine.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_config', full_name='hptuning.tasks_difine.task_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=777,
  serialized_end=869,
)

_PARAMETER_RESULT.fields_by_name['parameter_setting'].message_type = _PARAMETER
_PARAMETER_RESULT.fields_by_name['parameter_metrics'].message_type = _METRIC
_PARAMETER_RESULTS.fields_by_name['records'].message_type = _PARAMETER_RESULT
_HPTUNING_TASKS.fields_by_name['tasks'].message_type = _PARAMETER_RESULT
_HPTUNING_TASKS.fields_by_name['optimal'].message_type = _PARAMETER_RESULT
_CONFIG.fields_by_name['balancedDays'].message_type = _BALANCED_DATES
_TASKS_DIFINE.fields_by_name['params'].message_type = _PARA_DEFINE
_TASKS_DIFINE.fields_by_name['task_config'].message_type = _CONFIG
DESCRIPTOR.message_types_by_name['para_define'] = _PARA_DEFINE
DESCRIPTOR.message_types_by_name['flag'] = _FLAG
DESCRIPTOR.message_types_by_name['parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['metric'] = _METRIC
DESCRIPTOR.message_types_by_name['parameter_result'] = _PARAMETER_RESULT
DESCRIPTOR.message_types_by_name['parameter_results'] = _PARAMETER_RESULTS
DESCRIPTOR.message_types_by_name['hptuning_tasks'] = _HPTUNING_TASKS
DESCRIPTOR.message_types_by_name['balanced_dates'] = _BALANCED_DATES
DESCRIPTOR.message_types_by_name['config'] = _CONFIG
DESCRIPTOR.message_types_by_name['tasks_difine'] = _TASKS_DIFINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

para_define = _reflection.GeneratedProtocolMessageType('para_define', (_message.Message,), {
  'DESCRIPTOR' : _PARA_DEFINE,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.para_define)
  })
_sym_db.RegisterMessage(para_define)

flag = _reflection.GeneratedProtocolMessageType('flag', (_message.Message,), {
  'DESCRIPTOR' : _FLAG,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.flag)
  })
_sym_db.RegisterMessage(flag)

parameter = _reflection.GeneratedProtocolMessageType('parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.parameter)
  })
_sym_db.RegisterMessage(parameter)

metric = _reflection.GeneratedProtocolMessageType('metric', (_message.Message,), {
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.metric)
  })
_sym_db.RegisterMessage(metric)

parameter_result = _reflection.GeneratedProtocolMessageType('parameter_result', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER_RESULT,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.parameter_result)
  })
_sym_db.RegisterMessage(parameter_result)

parameter_results = _reflection.GeneratedProtocolMessageType('parameter_results', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER_RESULTS,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.parameter_results)
  })
_sym_db.RegisterMessage(parameter_results)

hptuning_tasks = _reflection.GeneratedProtocolMessageType('hptuning_tasks', (_message.Message,), {
  'DESCRIPTOR' : _HPTUNING_TASKS,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.hptuning_tasks)
  })
_sym_db.RegisterMessage(hptuning_tasks)

balanced_dates = _reflection.GeneratedProtocolMessageType('balanced_dates', (_message.Message,), {
  'DESCRIPTOR' : _BALANCED_DATES,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.balanced_dates)
  })
_sym_db.RegisterMessage(balanced_dates)

config = _reflection.GeneratedProtocolMessageType('config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.config)
  })
_sym_db.RegisterMessage(config)

tasks_difine = _reflection.GeneratedProtocolMessageType('tasks_difine', (_message.Message,), {
  'DESCRIPTOR' : _TASKS_DIFINE,
  '__module__' : 'parameter_tuning_pb2'
  # @@protoc_insertion_point(class_scope:hptuning.tasks_difine)
  })
_sym_db.RegisterMessage(tasks_difine)


DESCRIPTOR._options = None

_HPTUNING = _descriptor.ServiceDescriptor(
  name='hptuning',
  full_name='hptuning.hptuning',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=871,
  serialized_end=991,
  methods=[
  _descriptor.MethodDescriptor(
    name='gridsearch',
    full_name='hptuning.hptuning.gridsearch',
    index=0,
    containing_service=None,
    input_type=_TASKS_DIFINE,
    output_type=_HPTUNING_TASKS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopServer',
    full_name='hptuning.hptuning.stopServer',
    index=1,
    containing_service=None,
    input_type=_FLAG,
    output_type=_FLAG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HPTUNING)

DESCRIPTOR.services_by_name['hptuning'] = _HPTUNING

# @@protoc_insertion_point(module_scope)
